Feature/products
wecode-bootcamp-korea/20-1st-LIFEFRIENDS-backend pull request #1
Opened 2021-05-11 10:40 UTC by shinisgood

>wecode PR message template 및 체크 리스트 입니다.
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
models.py 작성
  - user, products, orders, reviews

## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-12 01:27 UTC, jamessoun93 requested changes

2021-05-12 01:27 UTC, jamessoun93 commented on users/models.py
> +    coupons         = models.CharField(max_length=200, blank=True)
쿠폰 기능을 만약 진행하시게 될 경우 유저당 쿠폰은 1회 발급 및 고유 쿠폰번호를 가질 수 있게끔 하실 예정이신가요?

2021-05-12 01:27 UTC, jamessoun93 commented on products/models.py
> +    product         = models.ManyToManyField('Product',through='Theme_Product')
컬럼명 및 필드명 주실때 헷갈리지 않도록 ForeignKey 는 단수형, M2M 필드는 복수형으로 선언해주세요.

2021-05-12 01:27 UTC, jamessoun93 commented on products/models.py
> +class Theme_Product(models.Model):
클래스명 확인해주세요!

2021-05-12 01:27 UTC, jamessoun93 commented on products/models.py
> +    description_img = models.CharField(max_length=2000)
컬럼명 확인해주세요. 어제 말씀드린대로 컬럼명은 명확하게 해당 컬럼에 어떤 값이 들어가야하는지를 한번에 파악할 수 있도록 지어주세요.

2021-05-12 01:27 UTC, jamessoun93 commented on products/models.py
> +class Product_Image(models.Model):
여기도 클래스명 확인해주세요.

2021-05-12 01:27 UTC, jamessoun93 commented on products/models.py
> +    url             = models.CharField(max_length=2000)
URL 은 `models.URLField()` 를 활용하실 수 있습니다.

2021-05-12 01:27 UTC, jamessoun93 commented on products/models.py
> +    product         = models.ManyToManyField('Product',through='Product_Size')
위에서 말씀드린대로 M2M 필드는 복수형으로 선언해주세요.

2021-05-12 01:27 UTC, jamessoun93 commented on products/models.py
> +class Product_Size(models.Model):
여기도 클래스명 확인해주세요.

2021-05-12 01:27 UTC, jamessoun93 commented on orders/models.py
> +class Selected_Product(models.Model):
클래스명 확인해주세요.

2021-05-12 02:43 UTC, shinisgood commented on users/models.py
> +    coupons         = models.CharField(max_length=200, blank=True)
쿠폰 발급 및 고유 쿠폰번호 부여를 위한 테이블 하나 생성하여 추가하겠습니다.

2021-05-12 02:50 UTC, shinisgood commented on products/models.py
> +    product         = models.ManyToManyField('Product',through='Theme_Product')
모든  M2M필드 반영 완료

2021-05-12 02:52 UTC, shinisgood commented on products/models.py
> +class Theme_Product(models.Model):
클래스명 어떤부분이 잘못 되었는지 잘 모르겠습니다 .. . ! 혹시 어떤거 일까요 ??!

2021-05-12 02:54 UTC, shinisgood commented on products/models.py
> +    description_img = models.CharField(max_length=2000)
description_img -> description_img_url 수정 했습니다 !

2021-05-12 02:55 UTC, shinisgood commented on products/models.py
> +class Theme_Product(models.Model):
언더바를 사용하면 안되는 건가요  ! !!  !

2021-05-12 02:56 UTC, shinisgood commented on products/models.py
> +class Product_Image(models.Model):
언더바 삭제 완료 했습니다 !

2021-05-12 02:56 UTC, shinisgood commented on products/models.py
> +    product         = models.ManyToManyField('Product',through='Product_Size')
복수형 수정 완료

2021-05-12 02:56 UTC, shinisgood commented on products/models.py
> +class Product_Size(models.Model):
언더바 삭제 완료 했습니다 !

2021-05-12 02:56 UTC, shinisgood commented on orders/models.py
> +class Selected_Product(models.Model):
언더바 삭제 완료 했습니다 !

2021-05-12 03:00 UTC, shinisgood commented on products/models.py
> +    url             = models.CharField(max_length=2000)
모든 URL필드 수정 완료 !

2021-05-13 01:23 UTC, jamessoun93 requested changes

2021-05-13 01:23 UTC, jamessoun93 commented on reviews/models.py
> +        db_table = 'reviewimages'
```suggestion
        db_table = 'review_images'
```

2021-05-13 01:23 UTC, jamessoun93 commented on products/models.py
> +        db_table = 'productssizes'
```suggestion
        db_table = 'products_sizes'
```

2021-05-13 01:23 UTC, jamessoun93 commented on products/models.py
> +        db_table = 'productimages'
```suggestion
        db_table = 'product_images'
```

2021-05-13 01:23 UTC, jamessoun93 commented on products/models.py
> +        db_table = 'themesproducts'
```suggestion
        db_table = 'themes_products'
```

2021-05-13 01:29 UTC, jamessoun93 commented on users/models.py
> +    coupons         = models.CharField(max_length=200, blank=True)
👍

2021-05-13 01:29 UTC, jamessoun93 commented on products/models.py
> +class Theme_Product(models.Model):
넵! 반대로 테이블명은 소문자형태로 언더바로 구분해주세요.

2021-05-13 01:30 UTC, jamessoun93 commented
테이블명만 수정해주시면 LGTM!

2021-05-13 04:50 UTC, jamessoun93 commented
LGTM

2021-05-13 04:50 UTC, merged