[20기 양영건] 카테고리 별 제품 분류 API
wecode-bootcamp-korea/20-1st-LIFEFRIENDS-backend pull request #3
Opened 2021-05-14 01:33 UTC by 111geon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 메뉴, 테마, 또는 카테고리를 선택했을 때 해당 그룹의 제품들을 정렬하여 보여주는 API 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 선택한 카테고리가 메뉴에 속하는지, 테마에 속하는지, 카테고리에 속하는지 판단하여
- 메뉴를 선택한 경우 해당 메뉴에 속한 테마 또는 카테고리를 모두 합쳐서 해당 메뉴에 속하는 제품들을 모두 get할 수 있도록
- 테마 또는 카테고리를 선택한 경우 해당 그룹에 해당하는 제품들을 모두 get할 수 있도록
- 한 후 인기도(clicks 수)를 기준으로 정렬하여 결과를 response

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- Null

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-14 07:21 UTC, jamessoun93 commented
conflict 해결해주세요~

2021-05-14 08:37 UTC, 111geon commented
conflict 해결하였습니다!

2021-05-17 01:32 UTC, jamessoun93 requested changes

2021-05-17 01:32 UTC, jamessoun93 commented on categories/views.py
> +        is_category = True if Category.objects.filter(name=category).exists() else False
- 이렇게 하시면 category가 뭐냐에 상관없이 불필요하게 테이블 3개를 매 요청마다 조회하게 되는데, 아래 if elif elif else 로 작성해놓으신 것을 보니 하나에 해당되면 다른 테이블은 볼 필요가 없다는 뜻이겠네요. 
- 이런경우 이렇게 카테고리 View에서 여러 테이블에 찾는 쿼리를 날리는 것보다 차라리 product list view 에서 query parameter 로 카테고리를 분류와 함께 프론트로부터 넘겨받아서 지정된 테이블 하나만 찾게끔 변경해주시는게 좋겠네요.
- ex) http://localhost:8000/products?category=선물추천
- ex) http://localhost:8000/products?theme=샐리프렌즈
- 이렇게 변경해주시면 전체적으로 로직이 바뀔텐데, 추가 리뷰는 해당 내용 반영되면 진행하겠습니다.

2021-05-17 16:49 UTC, 111geon commented on categories/views.py
> +        is_category = True if Category.objects.filter(name=category).exists() else False
products 앱에 query parameter를 이용하는 방식으로 수정사항 반영하였습니다.

2021-05-17 16:56 UTC, 111geon commented
수정사항을 반영한 이후로 response를 받는 속도가 좀 느려졌습니다. 
model 수정을 좀 하면서 총판매량인 sold나 총 리뷰개수인 review_count를 얻어오는 참조 과정이 좀 길어진 것 같다고는 생각이 듭니다.
제품의 각 사이즈별로 주문이 따로 있고, 이 주문의 입금여부 status를 확인하는 과정이 조금 긴 것 같습니다.
보통 웹사이트에서는 총 리뷰개수나 판매량을 그때 그때 합하기 보다 데이터베이스 내에 테이블을 따로 만들어서 저장해둘 것 같다고 생각이 드는데 혹시 맞나요?
현재 제가 짠 로직에서 속도가 느려질만한 부분이 있을지도 한번 봐주시면 감사 드리겠습니다.

2021-05-19 09:32 UTC, 111geon commented
코멘트 주신 내용들 모두 반영하였습니다.
로직이 전체적으로 모두 수정되었으며 속도는 훨씬 빨라졌네요.

2021-05-20 02:57 UTC, jamessoun93 requested changes

2021-05-20 02:57 UTC, jamessoun93 commented on products/views.py
> +                products += list(Product.objects.filter(theme=category))
Product.objects.

2021-05-20 02:57 UTC, jamessoun93 commented on products/views.py
> +            products = products.order_by(sort_criteria[sort])
이렇게 따로따로 기존 변수에 재할당하시는 방식으로 하지마시고, `filter(~~).annotate(~~).order_by(~~)` 의 형태로 한번에 처리해주세요. 참고로 annotate 문 안에 여러개의 kwargs 를 넣어줄 수 있으니 한번에 처리 가능합니다.

2021-05-20 02:57 UTC, jamessoun93 commented on products/views.py
> +            limit    = page * size
OFFSET 과 LIMIT 은 프론트엔드에서 계산해서 보내줄 수 있게끔 이야기하여 처리해주세요. 백엔드에서는 입력받은 LIMIT, OFFSET을 활용하여 바로 데이터베이스 쿼리를 할 수 있게끔요!

2021-05-20 02:57 UTC, jamessoun93 commented on users/validations.py
> +        return wrapper
현재 Validation 클래스에 있는 다른 유틸함수들과 validate_login 의 활용 목적이 조금 다르니 분리해주시는게 좋을 것 같습니다. 확장성을 고려하면 여러개의 데코레이터들이 생길 수 있기때문에 데코레이터만 모아놓는 파일로 분리해주시고 함수형태로 두셔도 좋습니다.

2021-05-20 02:57 UTC, jamessoun93 commented on users/views.py
> +        return JsonResponse({'MESSAGE': 'SUCCESS', 'USER_INFO': user_info}, status=200)
사이트에서 유저의 이름과 유저 이메일만 필요한 부분이 있어서 이 기능만 담고있는 view가 있는건가요?

2021-05-20 04:41 UTC, 111geon commented on users/views.py
> +        return JsonResponse({'MESSAGE': 'SUCCESS', 'USER_INFO': user_info}, status=200)
네 메인페이지와 네비게이션바에서 현재 접속중인 사용자의 이름과 이메일을 띄어주는 게 필요해서 만들었습니다. 이 부분은 "[20기 양영건] 로그인 회원가입 view 추가사항 작성" PR에서 작성되어 있습니다.

2021-05-20 04:47 UTC, 111geon commented on users/validations.py
> +        return wrapper
넵 분리하였습니다!

2021-05-20 04:58 UTC, 111geon commented on products/views.py
> +            products = products.order_by(sort_criteria[sort])
반영하였습니다

2021-05-20 05:06 UTC, 111geon commented on products/views.py
> +            limit    = page * size
LIMIT, OFFSET를 이용하여 바로 데이터베이스 쿼리를 할 수 있게 반영하였습니다. 프론트에서 OFFSET, LIMIT을 계산하는 건 현재 프론트 쪽에 시간이 없는 관계로 백엔드에서 계산하도록 하겠습니다.

2021-05-20 09:10 UTC, jamessoun93 approved these changes
LGTM

2021-05-20 09:11 UTC, merged